# Generated by Django 3.0.7 on 2020-06-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='name',
            new_name='title',
        ),
    ]
