# Generated by Django 3.0.7 on 2020-06-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_position_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='status',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
