# Generated by Django 3.0.7 on 2020-06-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200629_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
