# Generated by Django 3.0.7 on 2020-07-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectskill',
            name='required_skill',
            field=models.BooleanField(default=False),
        ),
    ]
