# Generated by Django 3.0.8 on 2020-07-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_position_key_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectSkill',
        ),
    ]
