# Generated by Django 3.0.8 on 2020-07-13 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_portfolio'),
        ('projects', '0016_delete_projectskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='key_skill',
            field=models.ForeignKey(help_text='Choose a key skill for this position', on_delete=django.db.models.deletion.CASCADE, related_name='key_skill', to='accounts.Skill'),
        ),
    ]
