# Generated by Django 3.0.7 on 2020-06-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200625_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
