# Generated by Django 3.0.6 on 2020-05-12 13:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='placeholder/default.jpg', max_length=255, null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
