# Generated by Django 3.1 on 2020-08-24 19:32

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200824_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/placeholder/default.jpg', max_length=255, null=True, upload_to=accounts.utils.user_directory_path),
        ),
    ]
