# Generated by Django 3.0.6 on 2020-05-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='is_skill',
            field=models.BooleanField(default=False),
        ),
    ]
